In [3]:
import pandas as pd
import numpy as np
from math import log2

In [17]:
info = pd.read_csv("GSE75688_final_sample_information.txt", sep="\t")
df = pd.read_csv("GSE75688_GEO_processed_Breast_Cancer_raw_TPM_matrix.txt", sep="\t", index_col=1)

In [18]:
del df['gene_id']
del df['gene_type']

In [15]:
tpdf = df.transpose()
tpdf

gene_name,TSPAN6,TNMD,DPM1,SCYL3,C1orf112,FGR,CFH,FUCA2,GCLC,NFYA,...,ERCC-00162,ERCC-00163,ERCC-00164,ERCC-00165,ERCC-00168,ERCC-00170,ERCC-00171,EC2,EC15,EC18
BC01_Pooled,2.33,0.0,60.70,47.93,4.79,0.00,0.06,46.54,11.61,9.51,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,14940.70,985.82,0.0
BC01_Tumor,1.25,0.0,28.44,4.43,1.67,0.00,9.64,20.97,5.97,4.81,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,45728.19,607.50,0.0
BC02_Pooled,43.96,0.0,74.73,9.89,10.87,0.52,0.00,46.30,8.72,19.39,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,10442.91,362.55,0.0
BC03_Pooled,7.64,0.0,41.41,7.61,0.92,0.00,0.00,8.57,5.51,0.28,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,94250.71,2949.35,0.0
BC03LN_Pooled,9.32,0.0,87.69,7.32,15.13,1.39,0.00,5.72,10.00,27.70,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,40823.13,1291.13,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
BC11_69,0.00,0.0,0.00,0.27,0.14,0.00,0.00,7.06,0.00,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,58840.26,2286.91,0.0
BC11_70,0.00,0.0,0.00,0.00,247.69,0.00,0.81,4.49,0.00,53.21,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,65246.34,2821.49,0.0
BC11_78,0.00,0.0,136.07,0.07,22.60,0.00,0.83,0.82,70.26,0.96,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,33465.11,1652.19,0.0
BC11_81,200.82,0.0,22.03,0.19,11.35,0.00,0.00,4.32,1.12,6.15,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,108901.35,3439.53,0.0
BC11_88,0.00,0.0,204.58,9.52,0.00,0.00,0.00,0.00,17.54,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,57492.01,1837.41,0.0

In [28]:
# some test to see if there's a row with tumor and non tumor in the same row
different_indexes = []
for row in info.index:
    
    samp_i1 = info.iloc[row][2]
    for val in info.iloc[row][3:]:
        if val != samp_i1:
            print("row:", info.iloc[row], "\n")
            different_indexes.append(info.iloc[row])
            break

row: sample     BC01_50
type            SC
index     nonTumor
index2     Stromal
index3     Stromal
Name: 10, dtype: object

row: sample     BC01_74
type            SC
index     nonTumor
index2     Stromal
index3     Stromal
Name: 18, dtype: object

row: sample     BC04_08
type            SC
index     nonTumor
index2     Stromal
index3     Stromal
Name: 26, dtype: object

row: sample     BC04_21
type            SC
index     nonTumor
index2      Immune
index3     Myeloid
Name: 33, dtype: object

row: sample     BC04_35
type            SC
index     nonTumor
index2      Immune
index3     Myeloid
Name: 44, dtype: object

row: sample     BC04_62
type            SC
index     nonTumor
index2      Immune
index3       Tcell
Name: 59, dtype: object

row: sample     BC04_66
type            SC
index     nonTumor
index2      Immune
index3       Tcell
Name: 62, dtype: object

row: sample     BC04_72
type            SC
index     nonTumor
index2      Immune
index3     Myeloid
Name: 65, dtype: object

row: sample     BC04_89
type            SC
index     nonTumor
index2      Immune
index3       Tcell
Name: 72, dtype: object

row: sample     BC04_96
type            SC
index     nonTumor
index2      Immune
index3       Tcell
Name: 77, dtype: object

row: sample     BC07_03
type            SC
index     nonTumor
index2      Immune
index3       Tcell
Name: 80, dtype: object

row: sample     BC07_04
type            SC
index     nonTumor
index2      Immune
index3     Myeloid
Name: 81, dtype: object

row: sample     BC07_07
type            SC
index     nonTumor
index2      Immune
index3     Myeloid
Name: 83, dtype: object

row: sample     BC07_09
type            SC
index     nonTumor
index2      Immune
index3     Myeloid
Name: 85, dtype: object

row: sample     BC07_16
type            SC
index     nonTumor
index2      Immune
index3       Tcell
Name: 88, dtype: object

row: sample     BC07_23
type            SC
index     nonTumor
index2     Stromal
index3     Stromal
Name: 91, dtype: object

row: sample     BC07_30
type            SC
index     nonTumor
index2      Immune
index3       Tcell
Name: 94, dtype: object

row: sample     BC07_42
type            SC
index     nonTumor
index2     Stromal
index3     Stromal
Name: 100, dtype: object

row: sample     BC07_44
type            SC
index     nonTumor
index2     Stromal
index3     Stromal
Name: 102, dtype: object

row: sample     BC07_50
type            SC
index     nonTumor
index2      Immune
index3     Myeloid
Name: 103, dtype: object

row: sample     BC07_52
type            SC
index     nonTumor
index2     Stromal
index3     Stromal
Name: 104, dtype: object

row: sample     BC07_55
type            SC
index     nonTumor
index2      Immune
index3     Myeloid
Name: 105, dtype: object

row: sample     BC07_56
type            SC
index     nonTumor
index2      Immune
index3       Tcell
Name: 106, dtype: object

row: sample     BC07_58
type            SC
index     nonTumor
index2      Immune
index3     Myeloid
Name: 108, dtype: object

row: sample     BC07_60
type            SC
index     nonTumor
index2      Immune
index3       Tcell
Name: 110, dtype: object

row: sample     BC07_61
type            SC
index     nonTumor
index2      Immune
index3       Tcell
Name: 111, dtype: object

row: sample     BC07_63
type            SC
index     nonTumor
index2      Immune
index3       Bcell
Name: 112, dtype: object

row: sample     BC07_68
type            SC
index     nonTumor
index2      Immune
index3       Bcell
Name: 116, dtype: object

row: sample     BC07_69
type            SC
index     nonTumor
index2      Immune
index3       Tcell
Name: 117, dtype: object

row: sample     BC07_79
type            SC
index     nonTumor
index2      Immune
index3     Myeloid
Name: 122, dtype: object

row: sample     BC07_80
type            SC
index     nonTumor
index2      Immune
index3       Bcell
Name: 123, dtype: object

row: sample     BC07_83
type            SC
index     nonTumor
index2      Immune
index3     Myeloid
Name: 124, dtype: object

row: sample     BC07_93
type            SC
index     nonTumor
index2      Immune
index3     Myeloid
Name: 127, dtype: object

row: sample     BC07_95
type            SC
index     nonTumor
index2      Immune
index3     Myeloid
Name: 128, dtype: object

row: sample    BC07_Pooled
type             Bulk
index        nonTumor
index2         Immune
index3         Immune
Name: 129, dtype: object

row: sample    BC07LN_03
type             SC
index      nonTumor
index2       Immune
index3        Bcell
Name: 131, dtype: object

row: sample    BC07LN_04
type             SC
index      nonTumor
index2       Immune
index3        Bcell
Name: 132, dtype: object

row: sample    BC07LN_05
type             SC
index      nonTumor
index2       Immune
index3        Bcell
Name: 133, dtype: object

row: sample    BC07LN_10
type             SC
index      nonTumor
index2      Stromal
index3      Stromal
Name: 135, dtype: object

row: sample    BC07LN_16
type             SC
index      nonTumor
index2       Immune
index3        Bcell
Name: 138, dtype: object

row: sample    BC07LN_18
type             SC
index      nonTumor
index2       Immune
index3        Bcell
Name: 139, dtype: object

row: sample    BC07LN_19
type             SC
index      nonTumor
index2       Immune
index3        Bcell
Name: 140, dtype: object

row: sample    BC07LN_22
type             SC
index      nonTumor
index2       Immune
index3        Bcell
Name: 141, dtype: object

row: sample    BC07LN_27
type             SC
index      nonTumor
index2       Immune
index3        Bcell
Name: 144, dtype: object

row: sample    BC07LN_49
type             SC
index      nonTumor
index2       Immune
index3        Bcell
Name: 154, dtype: object

row: sample    BC07LN_50
type             SC
index      nonTumor
index2       Immune
index3        Bcell
Name: 155, dtype: object

row: sample    BC07LN_53
type             SC
index      nonTumor
index2       Immune
index3        Bcell
Name: 158, dtype: object

row: sample    BC07LN_54
type             SC
index      nonTumor
index2       Immune
index3        Tcell
Name: 159, dtype: object

row: sample    BC07LN_59
type             SC
index      nonTumor
index2       Immune
index3        Bcell
Name: 161, dtype: object

row: sample    BC07LN_62
type             SC
index      nonTumor
index2       Immune
index3        Bcell
Name: 163, dtype: object

row: sample    BC07LN_64
type             SC
index      nonTumor
index2       Immune
index3        Bcell
Name: 164, dtype: object

row: sample    BC07LN_67
type             SC
index      nonTumor
index2       Immune
index3        Bcell
Name: 165, dtype: object

row: sample    BC07LN_68
type             SC
index      nonTumor
index2       Immune
index3        Bcell
Name: 166, dtype: object

row: sample    BC07LN_71
type             SC
index      nonTumor
index2       Immune
index3        Bcell
Name: 167, dtype: object

row: sample    BC07LN_81
type             SC
index      nonTumor
index2       Immune
index3        Bcell
Name: 171, dtype: object

row: sample    BC07LN_83
type             SC
index      nonTumor
index2       Immune
index3        Bcell
Name: 173, dtype: object

row: sample    BC07LN_84
type             SC
index      nonTumor
index2       Immune
index3        Bcell
Name: 174, dtype: object

row: sample    BC07LN_89
type             SC
index      nonTumor
index2       Immune
index3        Bcell
Name: 176, dtype: object

row: sample    BC07LN_90
type             SC
index      nonTumor
index2       Immune
index3        Tcell
Name: 177, dtype: object

row: sample    BC07LN_94
type             SC
index      nonTumor
index2       Immune
index3        Bcell
Name: 179, dtype: object

row: sample    BC07LN_96
type             SC
index      nonTumor
index2       Immune
index3        Bcell
Name: 181, dtype: object

row: sample    BC07LN_Pooled
type               Bulk
index          nonTumor
index2           Immune
index3           Immune
Name: 182, dtype: object

row: sample     BC03_03
type            SC
index     nonTumor
index2      Immune
index3       Tcell
Name: 183, dtype: object

row: sample     BC03_06
type            SC
index     nonTumor
index2      Immune
index3       Bcell
Name: 184, dtype: object

row: sample     BC03_24
type            SC
index     nonTumor
index2      Immune
index3       Bcell
Name: 194, dtype: object

row: sample     BC03_25
type            SC
index     nonTumor
index2      Immune
index3       Tcell
Name: 195, dtype: object

row: sample     BC03_28
type            SC
index     nonTumor
index2      Immune
index3       Bcell
Name: 197, dtype: object

row: sample     BC03_50
type            SC
index     nonTumor
index2      Immune
index3       Tcell
Name: 203, dtype: object

row: sample     BC03_53
type            SC
index     nonTumor
index2      Immune
index3       Bcell
Name: 204, dtype: object

row: sample     BC03_57
type            SC
index     nonTumor
index2      Immune
index3       Tcell
Name: 205, dtype: object

row: sample     BC03_58
type            SC
index     nonTumor
index2      Immune
index3       Tcell
Name: 206, dtype: object

row: sample     BC03_60
type            SC
index     nonTumor
index2      Immune
index3       Bcell
Name: 207, dtype: object

row: sample     BC03_66
type            SC
index     nonTumor
index2      Immune
index3       Tcell
Name: 208, dtype: object

row: sample     BC03_78
type            SC
index     nonTumor
index2      Immune
index3       Tcell
Name: 209, dtype: object

row: sample     BC03_81
type            SC
index     nonTumor
index2      Immune
index3       Bcell
Name: 210, dtype: object

row: sample     BC03_85
type            SC
index     nonTumor
index2      Immune
index3       Tcell
Name: 211, dtype: object

row: sample     BC03_86
type            SC
index     nonTumor
index2      Immune
index3       Bcell
Name: 212, dtype: object

row: sample     BC03_92
type            SC
index     nonTumor
index2      Immune
index3       Bcell
Name: 213, dtype: object

row: sample     BC03_93
type            SC
index     nonTumor
index2      Immune
index3       Bcell
Name: 214, dtype: object

row: sample     BC03_94
type            SC
index     nonTumor
index2      Immune
index3       Tcell
Name: 215, dtype: object

row: sample    BC03LN_01
type             SC
index      nonTumor
index2       Immune
index3        Bcell
Name: 217, dtype: object

row: sample    BC03LN_04
type             SC
index      nonTumor
index2       Immune
index3        Bcell
Name: 218, dtype: object

row: sample    BC03LN_06
type             SC
index      nonTumor
index2       Immune
index3        Bcell
Name: 220, dtype: object

row: sample    BC03LN_10
type             SC
index      nonTumor
index2       Immune
index3        Bcell
Name: 221, dtype: object

row: sample    BC03LN_11
type             SC
index      nonTumor
index2       Immune
index3        Bcell
Name: 222, dtype: object

row: sample    BC03LN_13
type             SC
index      nonTumor
index2       Immune
index3        Bcell
Name: 223, dtype: object

row: sample    BC03LN_14
type             SC
index      nonTumor
index2       Immune
index3        Bcell
Name: 224, dtype: object

row: sample    BC03LN_17
type             SC
index      nonTumor
index2       Immune
index3        Bcell
Name: 225, dtype: object

row: sample    BC03LN_20
type             SC
index      nonTumor
index2       Immune
index3        Bcell
Name: 227, dtype: object

row: sample    BC03LN_21
type             SC
index      nonTumor
index2       Immune
index3        Bcell
Name: 228, dtype: object

row: sample    BC03LN_26
type             SC
index      nonTumor
index2       Immune
index3        Bcell
Name: 231, dtype: object

row: sample    BC03LN_27
type             SC
index      nonTumor
index2       Immune
index3        Bcell
Name: 232, dtype: object

row: sample    BC03LN_31
type             SC
index      nonTumor
index2       Immune
index3        Bcell
Name: 234, dtype: object

row: sample    BC03LN_32
type             SC
index      nonTumor
index2       Immune
index3        Bcell
Name: 235, dtype: object

row: sample    BC03LN_34
type             SC
index      nonTumor
index2       Immune
index3        Bcell
Name: 236, dtype: object

row: sample    BC03LN_37
type             SC
index      nonTumor
index2       Immune
index3        Bcell
Name: 238, dtype: object

row: sample    BC03LN_38
type             SC
index      nonTumor
index2       Immune
index3        Bcell
Name: 239, dtype: object

row: sample    BC03LN_42
type             SC
index      nonTumor
index2       Immune
index3        Bcell
Name: 240, dtype: object

row: sample    BC03LN_44
type             SC
index      nonTumor
index2       Immune
index3        Bcell
Name: 241, dtype: object

row: sample    BC03LN_48
type             SC
index      nonTumor
index2       Immune
index3        Bcell
Name: 243, dtype: object

row: sample    BC03LN_49
type             SC
index      nonTumor
index2       Immune
index3        Bcell
Name: 244, dtype: object

row: sample    BC03LN_50
type             SC
index      nonTumor
index2       Immune
index3        Bcell
Name: 245, dtype: object

row: sample    BC03LN_51
type             SC
index      nonTumor
index2       Immune
index3        Bcell
Name: 246, dtype: object

row: sample    BC03LN_53
type             SC
index      nonTumor
index2       Immune
index3        Tcell
Name: 247, dtype: object

row: sample    BC03LN_56
type             SC
index      nonTumor
index2       Immune
index3        Tcell
Name: 248, dtype: object

row: sample    BC03LN_58
type             SC
index      nonTumor
index2       Immune
index3        Bcell
Name: 250, dtype: object

row: sample    BC03LN_62
type             SC
index      nonTumor
index2       Immune
index3        Bcell
Name: 252, dtype: object

row: sample    BC03LN_63
type             SC
index      nonTumor
index2       Immune
index3        Bcell
Name: 253, dtype: object

row: sample    BC03LN_64
type             SC
index      nonTumor
index2       Immune
index3        Bcell
Name: 254, dtype: object

row: sample    BC03LN_65
type             SC
index      nonTumor
index2       Immune
index3        Bcell
Name: 255, dtype: object

row: sample    BC03LN_68
type             SC
index      nonTumor
index2       Immune
index3        Bcell
Name: 256, dtype: object

row: sample    BC03LN_69
type             SC
index      nonTumor
index2       Immune
index3        Bcell
Name: 257, dtype: object

row: sample    BC03LN_70
type             SC
index      nonTumor
index2       Immune
index3        Bcell
Name: 258, dtype: object

row: sample    BC03LN_71
type             SC
index      nonTumor
index2       Immune
index3        Bcell
Name: 259, dtype: object

row: sample    BC03LN_72
type             SC
index      nonTumor
index2       Immune
index3        Bcell
Name: 260, dtype: object

row: sample    BC03LN_73
type             SC
index      nonTumor
index2       Immune
index3        Tcell
Name: 261, dtype: object

row: sample    BC03LN_74
type             SC
index      nonTumor
index2       Immune
index3        Bcell
Name: 262, dtype: object

row: sample    BC03LN_78
type             SC
index      nonTumor
index2       Immune
index3        Tcell
Name: 263, dtype: object

row: sample    BC03LN_79
type             SC
index      nonTumor
index2       Immune
index3        Bcell
Name: 264, dtype: object

row: sample    BC03LN_85
type             SC
index      nonTumor
index2       Immune
index3        Bcell
Name: 265, dtype: object

row: sample    BC03LN_91
type             SC
index      nonTumor
index2       Immune
index3        Tcell
Name: 267, dtype: object

row: sample    BC03LN_93
type             SC
index      nonTumor
index2       Immune
index3        Bcell
Name: 268, dtype: object

row: sample    BC03LN_95
type             SC
index      nonTumor
index2       Immune
index3        Bcell
Name: 269, dtype: object

row: sample     BC08_01
type            SC
index     nonTumor
index2     Stromal
index3     Stromal
Name: 271, dtype: object

row: sample     BC08_04
type            SC
index     nonTumor
index2     Stromal
index3     Stromal
Name: 272, dtype: object

row: sample     BC08_10
type            SC
index     nonTumor
index2      Immune
index3     Myeloid
Name: 275, dtype: object

row: sample     BC08_31
type            SC
index     nonTumor
index2     Stromal
index3     Stromal
Name: 279, dtype: object

row: sample     BC08_54
type            SC
index     nonTumor
index2     Stromal
index3     Stromal
Name: 284, dtype: object

row: sample     BC08_83
type            SC
index     nonTumor
index2     Stromal
index3     Stromal
Name: 289, dtype: object

row: sample     BC08_88
type            SC
index     nonTumor
index2     Stromal
index3     Stromal
Name: 290, dtype: object

row: sample     BC09_05
type            SC
index     nonTumor
index2      Immune
index3     Myeloid
Name: 294, dtype: object

row: sample     BC09_13
type            SC
index     nonTumor
index2     Stromal
index3     Stromal
Name: 295, dtype: object

row: sample     BC09_19
type            SC
index     nonTumor
index2      Immune
index3       Tcell
Name: 296, dtype: object

row: sample     BC09_21
type            SC
index     nonTumor
index2      Immune
index3       Tcell
Name: 297, dtype: object

row: sample     BC09_25
type            SC
index     nonTumor
index2      Immune
index3     Myeloid
Name: 298, dtype: object

row: sample     BC09_29
type            SC
index     nonTumor
index2      Immune
index3     Myeloid
Name: 299, dtype: object

row: sample     BC09_31
type            SC
index     nonTumor
index2      Immune
index3     Myeloid
Name: 300, dtype: object

row: sample     BC09_33
type            SC
index     nonTumor
index2      Immune
index3     Myeloid
Name: 301, dtype: object

row: sample     BC09_34
type            SC
index     nonTumor
index2      Immune
index3     Myeloid
Name: 302, dtype: object

row: sample     BC09_37
type            SC
index     nonTumor
index2      Immune
index3     Myeloid
Name: 303, dtype: object

row: sample     BC09_42
type            SC
index     nonTumor
index2      Immune
index3     Myeloid
Name: 304, dtype: object

row: sample     BC09_44
type            SC
index     nonTumor
index2      Immune
index3       Tcell
Name: 305, dtype: object

row: sample     BC09_45
type            SC
index     nonTumor
index2      Immune
index3     Myeloid
Name: 306, dtype: object

row: sample     BC09_46
type            SC
index     nonTumor
index2      Immune
index3     Myeloid
Name: 307, dtype: object

row: sample     BC09_48
type            SC
index     nonTumor
index2      Immune
index3     Myeloid
Name: 308, dtype: object

row: sample     BC09_49
type            SC
index     nonTumor
index2      Immune
index3       Tcell
Name: 309, dtype: object

row: sample     BC09_50
type            SC
index     nonTumor
index2      Immune
index3     Myeloid
Name: 310, dtype: object

row: sample     BC09_53
type            SC
index     nonTumor
index2      Immune
index3       Bcell
Name: 311, dtype: object

row: sample     BC09_57
type            SC
index     nonTumor
index2      Immune
index3       Tcell
Name: 312, dtype: object

row: sample     BC09_64
type            SC
index     nonTumor
index2      Immune
index3     Myeloid
Name: 313, dtype: object

row: sample     BC09_65
type            SC
index     nonTumor
index2      Immune
index3     Myeloid
Name: 314, dtype: object

row: sample     BC09_70
type            SC
index     nonTumor
index2     Stromal
index3     Stromal
Name: 315, dtype: object

row: sample     BC09_83
type            SC
index     nonTumor
index2      Immune
index3     Myeloid
Name: 316, dtype: object

row: sample     BC09_86
type            SC
index     nonTumor
index2      Immune
index3       Tcell
Name: 317, dtype: object

row: sample     BC09_92
type            SC
index     nonTumor
index2      Immune
index3     Myeloid
Name: 318, dtype: object

row: sample     BC09_93
type            SC
index     nonTumor
index2      Immune
index3       Tcell

row: sample     BC05_74
type            SC
index     nonTumor
index2     Stromal
index3     Stromal
Name: 476, dtype: object

row: sample     BC06_04
type            SC
index     nonTumor
index2      Immune
index3       Bcell
Name: 509, dtype: object

row: sample     BC06_08
type            SC
index     nonTumor
index2     Stromal
index3     Stromal
Name: 510, dtype: object

row: sample     BC06_21
type            SC
index     nonTumor
index2      Immune
index3       Bcell
Name: 512, dtype: object

row: sample     BC06_25
type            SC
index     nonTumor
index2      Immune
index3       Bcell
Name: 514, dtype: object

row: sample     BC06_26
type            SC
index     nonTumor
index2      Immune
index3       Bcell
Name: 515, dtype: object

row: sample     BC06_29
type            SC
index     nonTumor
index2      Immune
index3       Bcell
Name: 518, dtype: object

row: sample     BC06_40
type            SC
index     nonTumor
index2      Immune
index3       Bcell
Name: 521, dtype: object

row: sample     BC06_43
type            SC
index     nonTumor
index2     Stromal
index3     Stromal
Name: 522, dtype: object

row: sample     BC06_58
type            SC
index     nonTumor
index2      Immune
index3       Bcell
Name: 523, dtype: object

row: sample     BC06_61
type            SC
index     nonTumor
index2      Immune
index3       Bcell
Name: 525, dtype: object

row: sample    BC06_Pooled
type             Bulk
index        nonTumor
index2         Immune
index3         Immune
Name: 527, dtype: object

In [32]:
for sample in different_indexes:
    for val in sample:
        if val == 'Tumor':
            print(sample)
            print('\n')
            break

In [19]:
non_tumoral = []
tumoral = []

for row in info.index:
    
    for val in info.iloc[row][2:]:
        if val == 'Tumor':
            tumoral.append(info.iloc[row][0])
            break
        if val == 'nonTumor':
            non_tumoral.append(info.iloc[row][0])
            break

In [20]:
len(non_tumoral)

202

In [21]:
len(tumoral)

326

In [22]:
len(non_tumoral) == len(set(non_tumoral))

True

In [23]:
len(tumoral) == len(set(tumoral))

True

In [48]:
tpdf

gene_name,TSPAN6,TNMD,DPM1,SCYL3,C1orf112,FGR,CFH,FUCA2,GCLC,NFYA,...,ERCC-00162,ERCC-00163,ERCC-00164,ERCC-00165,ERCC-00168,ERCC-00170,ERCC-00171,EC2,EC15,EC18
BC01_Pooled,2.33,0,60.7,47.93,4.79,0,0.06,46.54,11.61,9.51,...,0,0,0,0,0,0,0,14940.7,985.82,0
BC01_Tumor,1.25,0,28.44,4.43,1.67,0,9.64,20.97,5.97,4.81,...,0,0,0,0,0,0,0,45728.2,607.5,0
BC02_Pooled,43.96,0,74.73,9.89,10.87,0.52,0,46.3,8.72,19.39,...,0,0,0,0,0,0,0,10442.9,362.55,0
BC03_Pooled,7.64,0,41.41,7.61,0.92,0,0,8.57,5.51,0.28,...,0,0,0,0,0,0,0,94250.7,2949.35,0
BC03LN_Pooled,9.32,0,87.69,7.32,15.13,1.39,0,5.72,10,27.7,...,0,0,0,0,0,0,0,40823.1,1291.13,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
BC11_69,0,0,0,0.27,0.14,0,0,7.06,0,0,...,0,0,0,0,0,0,0,58840.3,2286.91,0
BC11_70,0,0,0,0,247.69,0,0.81,4.49,0,53.21,...,0,0,0,0,0,0,0,65246.3,2821.49,0
BC11_78,0,0,136.07,0.07,22.6,0,0.83,0.82,70.26,0.96,...,0,0,0,0,0,0,0,33465.1,1652.19,0
BC11_81,200.82,0,22.03,0.19,11.35,0,0,4.32,1.12,6.15,...,0,0,0,0,0,0,0,108901,3439.53,0
BC11_88,0,0,204.58,9.52,0,0,0,0,17.54,0,...,0,0,0,0,0,0,0,57492,1837.41,0

In [24]:
count = 0
for sample in tpdf.index:
    if ('Pooled' in sample) or ('Tumor' in sample):
        print(sample)
        count+=1

BC01_Pooled
BC01_Tumor
BC02_Pooled
BC03_Pooled
BC03LN_Pooled
BC04_Pooled
BC05_Pooled
BC06_Pooled
BC07_Tumor
BC07LN_Pooled
BC08_Pooled
BC09_Pooled
BC10_Pooled
BC11_Pooled

In [60]:
count

14

In [25]:
from copy import deepcopy

df = deepcopy(tpdf)

In [26]:
df

gene_name,TSPAN6,TNMD,DPM1,SCYL3,C1orf112,FGR,CFH,FUCA2,GCLC,NFYA,...,ERCC-00162,ERCC-00163,ERCC-00164,ERCC-00165,ERCC-00168,ERCC-00170,ERCC-00171,EC2,EC15,EC18
BC01_Pooled,2.33,0.0,60.70,47.93,4.79,0.00,0.06,46.54,11.61,9.51,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,14940.70,985.82,0.0
BC01_Tumor,1.25,0.0,28.44,4.43,1.67,0.00,9.64,20.97,5.97,4.81,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,45728.19,607.50,0.0
BC02_Pooled,43.96,0.0,74.73,9.89,10.87,0.52,0.00,46.30,8.72,19.39,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,10442.91,362.55,0.0
BC03_Pooled,7.64,0.0,41.41,7.61,0.92,0.00,0.00,8.57,5.51,0.28,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,94250.71,2949.35,0.0
BC03LN_Pooled,9.32,0.0,87.69,7.32,15.13,1.39,0.00,5.72,10.00,27.70,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,40823.13,1291.13,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
BC11_69,0.00,0.0,0.00,0.27,0.14,0.00,0.00,7.06,0.00,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,58840.26,2286.91,0.0
BC11_70,0.00,0.0,0.00,0.00,247.69,0.00,0.81,4.49,0.00,53.21,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,65246.34,2821.49,0.0
BC11_78,0.00,0.0,136.07,0.07,22.60,0.00,0.83,0.82,70.26,0.96,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,33465.11,1652.19,0.0
BC11_81,200.82,0.0,22.03,0.19,11.35,0.00,0.00,4.32,1.12,6.15,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,108901.35,3439.53,0.0
BC11_88,0.00,0.0,204.58,9.52,0.00,0.00,0.00,0.00,17.54,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,57492.01,1837.41,0.0

In [27]:
#clean non-defined indexes 
for i, sample in enumerate(df.index):
    if (not(sample in tumoral)) and (not(sample in non_tumoral)):
        df = df.drop(sample)
        
df

gene_name,TSPAN6,TNMD,DPM1,SCYL3,C1orf112,FGR,CFH,FUCA2,GCLC,NFYA,...,ERCC-00162,ERCC-00163,ERCC-00164,ERCC-00165,ERCC-00168,ERCC-00170,ERCC-00171,EC2,EC15,EC18
BC01_Pooled,2.33,0.0,60.70,47.93,4.79,0.00,0.06,46.54,11.61,9.51,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,14940.70,985.82,0.0
BC02_Pooled,43.96,0.0,74.73,9.89,10.87,0.52,0.00,46.30,8.72,19.39,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,10442.91,362.55,0.0
BC03_Pooled,7.64,0.0,41.41,7.61,0.92,0.00,0.00,8.57,5.51,0.28,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,94250.71,2949.35,0.0
BC03LN_Pooled,9.32,0.0,87.69,7.32,15.13,1.39,0.00,5.72,10.00,27.70,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,40823.13,1291.13,0.0
BC04_Pooled,133.37,0.0,120.41,12.42,17.10,2.23,3.30,130.80,14.10,27.73,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,24540.58,854.53,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
BC11_69,0.00,0.0,0.00,0.27,0.14,0.00,0.00,7.06,0.00,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,58840.26,2286.91,0.0
BC11_70,0.00,0.0,0.00,0.00,247.69,0.00,0.81,4.49,0.00,53.21,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,65246.34,2821.49,0.0
BC11_78,0.00,0.0,136.07,0.07,22.60,0.00,0.83,0.82,70.26,0.96,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,33465.11,1652.19,0.0
BC11_81,200.82,0.0,22.03,0.19,11.35,0.00,0.00,4.32,1.12,6.15,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,108901.35,3439.53,0.0
BC11_88,0.00,0.0,204.58,9.52,0.00,0.00,0.00,0.00,17.54,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,57492.01,1837.41,0.0

In [28]:
df_log = (df+1).applymap(math.log2)

In [31]:
class_col = []
for sample in df_log.index:
    if sample in tumoral:
        class_col.append(1)
    elif sample in non_tumoral:
        class_col.append(0)
    else:
        print("bug on sample:", sample)

In [33]:
df_log['class'] = class_col

In [34]:
df_log

gene_name,TSPAN6,TNMD,DPM1,SCYL3,C1orf112,FGR,CFH,FUCA2,GCLC,NFYA,...,ERCC-00163,ERCC-00164,ERCC-00165,ERCC-00168,ERCC-00170,ERCC-00171,EC2,EC15,EC18,class
BC01_Pooled,1.735522,0.0,5.947199,5.612647,2.533563,0.000000,0.084064,5.571070,3.656496,3.393691,...,0.0,0.0,0.0,0.0,0.0,0.0,13.867057,9.946643,0.0,1
BC02_Pooled,5.490570,0.0,6.242793,3.444932,3.569248,0.604071,0.000000,5.563768,3.280956,4.349790,...,0.0,0.0,0.0,0.0,0.0,0.0,13.350374,8.506010,0.0,1
BC03_Pooled,3.111031,0.0,5.406333,3.106013,0.941106,0.000000,0.000000,3.258519,2.702658,0.356144,...,0.0,0.0,0.0,0.0,0.0,0.0,16.524231,11.526670,0.0,1
BC03LN_Pooled,3.367371,0.0,6.470700,3.056584,4.011675,1.257011,0.000000,2.748461,3.459432,4.842979,...,0.0,0.0,0.0,0.0,0.0,0.0,15.317135,10.335536,0.0,1
BC04_Pooled,7.070067,0.0,6.923743,3.746313,4.177918,1.691534,2.104337,7.042207,3.916477,4.844486,...,0.0,0.0,0.0,0.0,0.0,0.0,14.582941,9.740675,0.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
BC11_69,0.000000,0.0,0.000000,0.344828,0.189034,0.000000,0.000000,3.010780,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,15.844541,11.159815,0.0,1
BC11_70,0.000000,0.0,0.000000,0.000000,7.958205,0.000000,0.855990,2.456806,0.000000,5.760487,...,0.0,0.0,0.0,0.0,0.0,0.0,15.993631,11.462753,0.0,1
BC11_78,0.000000,0.0,7.098769,0.097611,4.560715,0.000000,0.871844,0.863938,6.155021,0.970854,...,0.0,0.0,0.0,0.0,0.0,0.0,15.030413,10.691037,0.0,1
BC11_81,7.656925,0.0,4.525443,0.250962,3.626439,0.000000,0.000000,2.411426,1.084064,2.837943,...,0.0,0.0,0.0,0.0,0.0,0.0,16.732676,11.748415,0.0,1
BC11_88,0.000000,0.0,7.683556,3.395063,0.000000,0.000000,0.000000,0.000000,4.212569,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,15.811099,10.844243,0.0,1

In [35]:
from sklearn.svm import SVC
from sklearn.metrics import classification_report, confusion_matrix
from sklearn import metrics


def get_x(df):
    return df.loc[:, df.columns != 'class']
    
def get_y(df):
    return df.loc[:, ['class']].T.values[0]

In [36]:
X_train = get_x(df_log)
y_train = get_y(df_log)

clf = SVC(gamma='auto', probability=True)
clf.fit(X_train, y_train)

# accuracy
clf.score(X_train, y_train)

1.0

In [55]:
rank = pd.read_csv("/home/colombelli/Documents/Experiments11_mai/BRCA/Hyb_stb_borda/fold_1/agg_ranking_th150.csv")
genes = list(rank['Unnamed: 0'][0:150])

donthave = []
have = []
for gene in genes:
    
    try:
        df_log[gene]
        have.append(gene)
    except:
        donthave.append(gene)
        
len(have)

143

In [56]:
df_sel = df_log[have+['class']]

In [57]:
X_train = get_x(df_sel)
y_train = get_y(df_sel)

clf = SVC(gamma='auto', probability=True)
clf.fit(X_train, y_train)

# accuracy
clf.score(X_train, y_train)

0.9639468690702088

In [58]:
import rpy2.robjects as robjects
from rpy2.robjects import pandas2ri
from rpy2.robjects.conversion import localconverter

In [59]:

def load_RDS(file_path):

    read_RDS = robjects.r['readRDS']
    return read_RDS(file_path)



def load_csv(file_path):
    return pd.read_csv(file_path, index_col=0)



def pandas_to_r(df):

    with localconverter(robjects.default_converter + pandas2ri.converter):
        r_from_pandas_df = robjects.conversion.py2rpy(df)
    return r_from_pandas_df



def r_to_pandas(df):
    with localconverter(robjects.default_converter + pandas2ri.converter):
            pandas_from_r_df = robjects.conversion.rpy2py(df)
    return pandas_from_r_df

In [60]:
main = r_to_pandas(load_RDS("/home/colombelli/Documents/datasets/research/brca.rds"))

In [68]:
main[have +['class']]
df_sel

gene_name,MIR4508,CA4,IBSP,RERGL,CST1,CCL11,ANGPTL7,TNMD,MAP1LC3C,PLAC1,...,ABCA5,EPHB1,ANGPT1,DEFB132,SLC7A4,ETS2,MEIS2,APBA1,KAT2B,class
BC01_Pooled,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000,...,3.744161,1.350497,0.000000,0.0,0.000000,3.000000,0.000000,0.000000,0.411426,1
BC02_Pooled,0.0,0.0,0.389567,0.0,1.550901,0.0,0.0,0.0,0.0,6.378685,...,3.150560,0.000000,0.000000,0.0,4.040016,4.790772,0.632268,1.144046,0.831877,1
BC03_Pooled,0.0,0.0,0.000000,0.0,3.046142,0.0,0.0,0.0,0.0,0.000000,...,0.124328,0.000000,0.000000,0.0,0.000000,3.537296,0.000000,0.000000,0.000000,1
BC03LN_Pooled,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000,...,1.475085,0.000000,0.000000,0.0,0.000000,0.070389,0.000000,0.000000,3.565597,1
BC04_Pooled,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,2.678072,...,1.790772,0.000000,0.000000,0.0,0.000000,2.207893,0.000000,0.000000,3.326250,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
BC11_69,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000,...,0.000000,0.000000,0.163499,0.0,0.000000,4.669594,0.000000,0.000000,0.000000,1
BC11_70,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000,...,1.150560,0.000000,0.000000,0.0,0.000000,0.000000,4.201634,0.000000,0.000000,1
BC11_78,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000,...,3.301588,0.000000,0.505891,0.0,0.000000,5.026357,4.133399,0.000000,0.000000,1
BC11_81,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000,...,0.000000,0.000000,0.000000,0.0,0.000000,0.823749,7.030777,0.000000,0.000000,1
BC11_88,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000,...,7.917909,0.000000,0.000000,0.0,0.000000,2.906891,1.664483,1.117695,0.000000,1

In [69]:
cols = []
for col in df_sel:
    if col not in cols:
        cols.append(col)
        
    else:
        print(col)

LCN6

In [75]:
del df_sel['LCN6']

In [79]:
del main['LCN6']

In [80]:
main[have +['class']]

KeyError: "['LCN6'] not in index"

In [81]:
have2 = []
for l in have:
    if l != 'LCN6':
        have2.append(l)

In [82]:
main[have2 +['class']]

,MIR4508,CA4,IBSP,RERGL,CST1,CCL11,ANGPTL7,TNMD,MAP1LC3C,PLAC1,...,ABCA5,EPHB1,ANGPT1,DEFB132,SLC7A4,ETS2,MEIS2,APBA1,KAT2B,class
TCGA.A7.A0CE.11A.21R.A089.07,1.023422,3.182868,0.212920,4.226681,0.000000,0.954446,2.364791,3.243871,2.269264,0.254117,...,3.372432,3.567462,1.890646,0.979544,2.392482,6.471708,3.381626,2.947514,3.466688,0.0
TCGA.A7.A0CH.11A.32R.A089.07,1.443516,6.371363,0.000000,4.703450,1.637875,0.061269,3.355357,6.016510,2.893386,0.650968,...,3.238917,2.644617,4.259257,3.458708,2.771764,6.339371,3.230928,2.562294,4.087900,0.0
TCGA.A7.A0D9.11A.53R.A089.07,2.730774,7.016745,0.000000,3.709476,0.289902,0.000000,0.682235,7.256551,4.078326,0.070488,...,3.840555,0.691594,6.016819,5.644271,2.954585,6.658885,3.239088,2.487251,5.394331,0.0
TCGA.A7.A0DB.11A.33R.A089.07,2.619353,5.806758,0.000000,4.765540,0.306763,0.474391,0.487787,3.821239,5.395368,0.214021,...,3.570243,0.657871,4.364030,3.491731,1.027150,6.205687,3.450635,2.896322,4.857750,0.0
TCGA.A7.A0DC.11A.41R.A089.07,0.908018,6.303658,0.107185,3.766167,0.646245,0.000000,2.602076,5.014065,2.631919,0.284454,...,4.002768,2.804124,5.395255,6.645991,2.936931,6.383289,3.449470,2.841733,4.640874,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
TCGA.WT.AB44.01A.11R.A41B.07,0.000000,1.666267,0.144204,1.218694,6.613787,4.327344,0.291830,1.315478,0.987071,0.603941,...,2.464656,0.585777,0.157900,0.351759,4.248274,5.841747,2.604364,2.938858,2.072777,1.0
TCGA.XX.A899.01A.11R.A36F.07,6.109105,3.253125,2.429627,1.563874,4.248985,2.015079,1.159073,0.850290,2.516335,1.786991,...,3.384577,1.640723,1.636050,0.777956,0.330383,6.556951,3.253993,1.970006,3.841727,1.0
TCGA.XX.A89A.01A.11R.A36F.07,6.493587,3.491781,2.197759,0.743808,5.838259,2.941052,0.144274,5.521037,1.572728,1.138805,...,2.328057,0.986811,3.176970,2.133026,1.083659,5.923554,3.027017,1.685501,4.053263,1.0
TCGA.Z7.A8R5.01A.42R.A41B.07,0.832442,0.066752,1.093227,2.751624,2.522511,4.026946,0.620313,0.532015,0.401547,1.013787,...,2.864043,1.306196,0.715878,0.270495,0.772987,5.150529,2.423118,1.361064,2.285211,1.0
TCGA.Z7.A8R6.01A.11R.A41B.07,1.527732,0.000000,2.972670,0.255510,7.328767,1.278114,0.210493,0.296542,0.528462,3.295732,...,0.960768,0.761785,0.448565,0.320474,0.702179,4.575976,1.664009,1.098501,2.053766,1.0

In [84]:
X_train = get_x(main[have2 +['class']])
y_train = get_y(main[have2 +['class']])

X_test = get_x(df_sel)
y_test = get_y(df_sel)


clf = SVC(gamma='auto', probability=True)

clf.fit(X_test, y_test)
clf.score(X_train, y_train)

0.9082792207792207

In [85]:
clf2 = SVC(gamma='auto', probability=True)
clf2.fit(X_train, y_train)
clf2.score(X_test, y_test)

0.618595825426945